version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    ports:
      - '8084:8080'
    volumes:
      - 'volume_jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  volume_jenkins:
    driver: local
