version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    ports:
      - '8084:8080'
    volumes:
      - '~/volumes/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
