version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    restart: on-failure
    privileged: true
    user: root
    networks:
      - jenkins
    ports:
      - '8084:8080'
    volumes:
      - 'volume_jenkins3:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  volume_jenkins3:
    driver: local

networks:
  jenkins:
    driver: bridge